[manifest]
version = "1.0.0"
dump_lua = true
priority = 214748364

[[patches]] #G.Game.current_round
[patches.pattern]
target = 'game.lua'
pattern = '''
reroll_cost_increase = 0,
'''
position = 'after'
match_indent = true
payload = '''
jest_magick_joker_card = {suit = 'Spades'},
jest_highest_scored_mult = {amount = 0, trigger = true},
jest_you_broke_it_card = {rank = nil, enhancement = nil, id = nil},	
'''

[[patches]]  
[patches.pattern]
target = 'game.lua'
pattern = '''
reset_castle_card()
'''
position = 'after'
match_indent = true
payload = '''
reset_jest_magick_joker_card()
reset_jest_you_broke_it_card()
'''

[[patches]] #G.GAME 
[patches.pattern]
target = 'game.lua'
pattern = '''
unused_discards = 0,'''
position = 'after'
match_indent = true 
payload = '''
all_in_jest = {
	apply = { -- Specific triggers for cards
		v_aij_gold_medal_been_used = false,
		ticket_trigger = true,
	}, 
	dizzard_shop = false,
	pit_blind_ante = 4,
	blind_tags = {has_multiple = false, Small = {two = nil, three = nil}, Big = {two = nil, three = nil}, selected_index = nil},
	advanced_hand_usage_run = {},
	advanced_hand_usage = {},
	AIJAnimated = {
		c_aij_scopophobia = { frames_per_row = 18, frames = 144, start_frame = 126, fps = 12, hold = { frames = 2, max_frames = 144, min_frames = 128, min_start_frames = 126, hold_for_min = 12, hold_for_max = 35 } },
		j_aij_electric_snow = { frames_per_row = 25, frames = 382, start_frame = 375, fps = 16, },
		j_aij_wireframe = { frames_per_row = 25, frames = 440, start_frame = 430, fps = 10, },
		j_aij_baddata = { 
			frames_per_row = 25, 
			frames = 456, 
			start_frame = 441,
			fps = 10,
			layers = {
				soul_pos = {
					frames_per_row = 25, 
					frames = 477, 
					start_frame = 456,
					fps = 10,
				},
				aij_floating_sprite_1 = {
					frames_per_row = 25, 
					frames = 491, 
					start_frame = 485,
					fps = 10,
				}
			}
		},
		m_aij_simulated = {frames_per_row = 10, frames = 20, start_frame = 10, fps = 10,}
	},
	patches_sprites = {},
	reset_score = {chips = false, mult = false, chip_total = false, blind_total = false},
	secret_hands = {},
	gold_tag_rate = 1,
},
-- move these into all_in_jest at some point
jest_unused_hands = 0,
jest_legendary_pool = {in_shop = false, rate = 1.00},
jest_stored_memory_card = nil,
jest_change_booster_options = {op = {add = 0, mult = 0, div = 0, sub = 0}, trigger = false, option = "", pack_choices = 0}, -- both, pick, or size
jest_void_planet_ante = false,
jest_kasperle_voucher_ante = false,
jest_kilroy_sold = 0,
jest_bought_jokers = 0,
jest_magic_mirror_trigger = true,
jest_toothy_joker_tarots = 0,
jest_jester_zombie_trigger = false,
jest_omlette_appearence_eggs = 0,
jest_free_stultor_rerolls = 0,
jest_fairy_edition_rate = 1,
['jest_upgrade_tab'] = false,
previous_jest_upgrade_tab = false,
shop_galloping_dominoed = false,
temp_create_card = {},
'''

[[patches]] #Colors
[patches.pattern]
target = 'functions/misc_functions.lua'
pattern = '''enhanced = G.C.SECONDARY_SET.Enhanced'''
position = 'before'
payload = '''
jest_inherent = HEX("b7e1d7"),
jest_glitter = HEX("ff97ff"),
'''
match_indent = true